export const local_host = "http://192.168.1.195:8080/";
export const upcoming_events_pageable_api =
  local_host + "events/upcoming-events-paging?page=0";
export const events_images = local_host + "images";
export const previous_events_pageable_api =
  local_host + "events/previous-events-paging?page=0";
export const search_event_api = local_host + "events/search-event/";
export const add_event_api = local_host + "events";
export const save_event = local_host + "action/save";
export const unsave_event = local_host + "action/unsave";
export const reserve_event = local_host + "action/register";
export const upcoming_events_api = local_host + "events/upcoming-events";
export const previous_events_api = local_host + "events/previous-events";
export const event_details_api = local_host + "events";
export const cancel_reservation_url = local_host + "action/cancelReservation";
export const update_event_api = local_host + "events/update";
export const attended_events_api = local_host + "action/attendedEvents";
export const saved_events_api = local_host + "action/savedEvents";
export const organized_events_api = local_host + "action/organizedEvents";
export const attendees_list_api = local_host + "action/attendees";
